# Generated by Django 4.0.2 on 2022-02-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=10, unique=True, verbose_name='Identificación')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Persona'), (2, 'Empresa')], default=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=30, unique=True, verbose_name='Número de matricula')),
                ('cadastral_id', models.CharField(max_length=30, verbose_name='Cédula catastral')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Urbano'), (2, 'Rural')], default=1, verbose_name='Tipo')),
                ('owners', models.ManyToManyField(to='properties.Owner')),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
            },
        ),
    ]
